apiVersion: v1
kind: Namespace
metadata:
  name: prod

---
apiVersion: v1 
kind: ResourceQuota
metadata:
  namespace: prod
  name: prod-quota
spec:
  hard:
    requests.cpu: '1' # Equal to 1000m 
    requests.memory: '1Gi'
    limits.cpu: '2'
    limits.memory: '2Gi'