apiVersion: v1
kind: Pod
metadata:
  name: mybusybox-volume
  labels:
    app: mybusybox-volume
spec:
  containers:
  - name: busybox-container-vol
    image: busybox:1.36.1
    command:
      - 'sh'
      - '-c'
      -  'sleep 1200'
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: db-secrets
        mountPath: /etc/db
  volumes:
    - name: db-secrets
      secret:
        secretName: dbsec

