apiVersion: v1
kind: Pod
metadata:
  name: myapp-empty-containers
spec:
  containers:
  - name: myapp-empty-rw
    image: busybox:latest
    command:
      - 'sh'
      - '-c'
      - 'sleep 3600'
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: temp-volume
        mountPath: /usr/share/temp
  - name: myapp-empty-ro
    image: busybox:latest
    command:
      - 'sh'
      - '-c'
      - 'sleep 3600'
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: temp-volume
        mountPath: /usr/share/temp
        readOnly: true
  #Volume on pod confiquration. So you declare there
  volumes:
    - name: temp-volume
      emptyDir: {}