apiVersion: v1
kind: Pod
metadata:
  name: color-api-health
  labels:
    app.kubernetes.io/name: color-api-health
spec:
  containers:
  - name: color-api-health
    image: lmacademy/color-api:1.2.0
    resources:
      limits:
        cpu: '500m'
        memory: '512Mi'
    ports:
      - containerPort: 80
    ## SEtting up a delay probe 
    env:
      - name: DELAY_STARTUP
        value: 'true'
    startupProbe:
      httpGet:
        path: /health
        port: 80
      failureThreshold: 2
      periodSeconds: 3
