apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-api-dep
spec:
  replicas: 10
  selector:
    matchLabels:
      app: color-api
  template:
    metadata:
      labels:
        app: color-api
    spec:
      containers:
      - name: color-container
        image: lmacademy/color-api:1.1.0
        ports:
        - containerPort: 80
