apiVersion: v1
kind: Pod 
metadata:
  name: nginx-ingress
  labels:
    app: ingress
spec:
  containers:
    - image: nginx:latest
      name: nginx-container
      ports:
        - containerPort: 80
---
#For documentation, equivelant to imperative cmd 
# kubectl expose pod nginx-ingress --type=NodePort --port=80
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector:
    app: ingress
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80